site_name: 安迪小站
dev_addr: '127.0.0.1:8090'

# Configuration
theme:
  name: null
  custom_dir: material

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: black
    accent: black
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"

# Page tree
nav:
  - Home: index.md
  - Post:
    - Admonition: post.md
  - Travel:
    - travel: travel.md
  - Note:
    - Note导航 : note.md
    - 手机相关 : note/phone.md
  - Photo:
    - 照片导航: photo.md
  - Video:
    - Admonition: video.md
  - About: 
    - 链接导航: links.md
    - 合作联系: contact.md