site_name: 安迪小站
dev_addr: '127.0.0.1:8090'

# Configuration
theme:
  name: null
  custom_dir: material

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: black
    accent: black
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"

# Page tree
nav:
  - 主页: index.md
  - 博文:
    - 索引: post.md
  - 旅行:
    - ✈️ travel: travel.md
  - 笔记:
    - 📑 笔记导航: note.md
    - 📱 手机相关: note/phones/
    - 🎮 Switch: note/switch/
  - 游戏:
    - 🎮 Game: game.md
  - 视频:
    - 🎥 视频: video.md
  - 收藏: 
    - 💖 收藏: favlist.md
  - 表情包: 
    - 💩 沙雕/装逼: meme.md
    - 📑 模板: meme/meme_template.md
    - 🐼 熊猫: meme/meme_panda/
  - 关于: 
    - 链接导航: links.md
    - 合作联系: contact.md

google_analytics: ['UA-66508870-1', 'hi-andy.com']